spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: ml_app_consultorio

  main:
    allow-bean-definition-overriding: true
  jackson:
    property-naming-strategy: SNAKE_CASE
