spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ml_app_consultorio
    password: ml_app_user4
    username: ml_app_user4
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true